version: "3.7"

services:
    app:
        image: "laratest/app:${TAG:-latest}"
        build:
            args:
                user: testusr
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        container_name: test-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - test-network

    web:
        image: nginx:1.19.4
        container_name: test-nginx
        restart: unless-stopped
        ports:
            - ${SERVER_PORT:-80}:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - test-network

    pgsql:
        image: postgres:9.6
        container_name: test-pgsql
        restart: unless-stopped
        expose:
            - 5432
        ports:
            - ${DB_PORT:-5432}:5432
        volumes:
            - dbpgsql:/docker-entrypoint-initdb.d/
        environment:
            POSTGRES_USER: ${DB_USERNAME:-postgres}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-cafecomleite}
            POSTGRES_DB: ${DB_DATABASE:-sieven}
        networks:
            - test-network

    adminer:
        image: adminer
        restart: always
        ports:
            - ${ADMINER_PORT_DB:-8181}:8080
        environment:
            - ADMINER_DEFAULT_SERVER=pgsql
            - ADMINER_DESIGN=price
        networks:
            - test-network

    mailhog:
        image: mailhog/mailhog
        logging:
            driver: "none"
        ports:
            - ${MAIL_PORT:-1025}:1025
            - ${MAILHOG_PORT:-8025}:8025
        networks:
            - test-network

networks:
    test-network:
        driver: bridge

volumes:
    dbpgsql:
