services:
  - name: app
    type: web
    buildCommand: |
      docker build -t test-app
    startCommand: |
      docker build -p 8080:80 test-app
    envVars:
      - key: SERVICE_NAME
        value: app
      - key: SERVICE_TAGS
        value: dev
    workDir: /var/www
    volumeMounts:
      - source: .
        destination: /var/www
      - source: ./php/local.ini
        destination: /usr/local/etc/php/conf.d/local.ini

  - name: webserver
    type: web
    buildCommand: |
      docker build -t test-nginx .
    startCommand: |
      docker run -p 80:80 -p 443:443 test-nginx
    volumeMounts:
      - source: .
        destination: /var/www
      - source: ./nginx/conf.d/
        destination: /etc/nginx/conf.d/

networks:
  - name: app-network
    type: bridge